### ISSUE TITLE
db.dropall()

### ISSUE THREAD

**Issue by tko22** [hack4impact-uiuc/childs-play-tool#43]
This deletes everything from the database. Even though this may be the intended behavior, it's extremely unsafe to have that as an endpoint. I'm assuming this was done for the purpose of development, but let's remove that so it would never even have the chance of slipping to production

https://github.com/hack4impact-uiuc/childs-play-tool/blob/9503efecfea61363f19138ed08c1ae49983de889/backend/api/views/games.py#L117

**Comment by angadgarg25** [comment]
Resolved
