### ISSUE TITLE
Save Search to PDF

### ISSUE THREAD

**Issue by HRimaw2** [hack4impact-uiuc/childs-play-tool#76]
Essentially, how to convert the results page into a pdf that can be saved. We're thinking of wrapping the right click save as pdf function, but also should ensure the functionality on mobile.

More details to come from Angad.

**Comment by angadgarg25** [comment]
Yeah basically just have a button on the results page that when clicked, converts the results page to a PDF and downloads the pdf from the browser. Some links that may be useful:
https://www.npmjs.com/package/generate-pdf
https://stackoverflow.com/questions/44989119/generating-a-pdf-file-from-react-components

I've never done this before though, so there might be better ways.

**Comment by arpanlaha** [comment]
Abandoned
