### ISSUE TITLE
Update/cards components (very basic functionality)

### ISSUE THREAD

**Issue by Feeshay** [hack4impact-uiuc/childs-play-tool#8]
Updating component should have a button and upload field

Descriptions should have a title, tags, summary, and full description. Add protagonist and other features later, maybe when we split to cards/full description.

**Comment by HRimaw2** [comment]
<img width="529" alt="screen shot 2018-10-06 at 5 39 53 pm" src="https://user-images.githubusercontent.com/22106052/46646598-9f958a80-cb50-11e8-990b-cc4272ed70c2.png">
This is the updated design with the consoles in their separate categories
